Uncomment the bellow line if you do not use Colab

In [1]:

#!pip3 install torch

In [2]:
import torch
import numpy as np

In [3]:
print(torch.__version__)

1.7.0+cu101


#**Tensor**

###Initializing a tensor

In [4]:
#Initializing a tensor
a = torch.Tensor([2,3])
print(a.size())
print(a)

torch.Size([2])
tensor([2., 3.])


In [5]:
a.type()

'torch.FloatTensor'

In [6]:
t = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(t)
print(t.t())
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


###creating scalar tensor

In [7]:
a = torch.tensor(20)
print(a)
print(a.size())

tensor(20)
torch.Size([])


###Converting scalar to python number

In [8]:
print(a.item())
print(type(a.item()))

20
<class 'int'>


###Creating a float tensor

In [9]:
a = torch.tensor([2.0,3])
a.type()

'torch.FloatTensor'

###Providing the data type while creating the tensor

In [10]:
a = torch.tensor([2,3],dtype=torch.int32)
a.type()

'torch.IntTensor'

###Just like numpy, creating a tensor by copying another tensor results to pointing to same memory location

In [11]:
a = torch.tensor([2.0,3])
b = a
b[0]=11
print(a)
print(b)

tensor([11.,  3.])
tensor([11.,  3.])


###2D tensor

In [12]:
a = torch.tensor([[1,2],[3,4]])

###Creating and initializing a tensor with random values

In [13]:
a = torch.rand(3,4)
print(a)

tensor([[0.4654, 0.2963, 0.3619, 0.5010],
        [0.3524, 0.8792, 0.8713, 0.7838],
        [0.7502, 0.2786, 0.5487, 0.6439]])


###Creating and initializing a float tensor with zeros

In [14]:
a = torch.zeros((4,5),dtype=torch.float32)
print(a)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


###Creating an Identity tensor

In [15]:
a = torch.eye(4,4)
print(a)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


#**Tensor Operations**

###Addition of two tensor

In [16]:
x = torch.rand(3,3)
y = torch.rand(3,3)
z = x+y
print(z)

tensor([[1.1366, 0.6893, 0.7349],
        [0.8152, 0.9359, 0.9783],
        [0.9523, 1.5633, 0.0734]])


###Addition of two tensor (alternative)

In [ ]:
z = x.add(y)
print(z)

###Inplace addition of two tensor

In [17]:
print(x)

x.add_(y)

print(x)

tensor([[0.5995, 0.4100, 0.4608],
        [0.6049, 0.7387, 0.5486],
        [0.6874, 0.7719, 0.0089]])
tensor([[1.1366, 0.6893, 0.7349],
        [0.8152, 0.9359, 0.9783],
        [0.9523, 1.5633, 0.0734]])


###Element wise multiplication

In [18]:
print(x*y)

tensor([[0.6105, 0.1926, 0.2015],
        [0.1714, 0.1846, 0.4204],
        [0.2523, 1.2373, 0.0047]])


###Matrix multiplication

In [19]:
z = torch.matmul(x,y[:,0])
print(z)
z.size()

tensor([0.9502, 0.8940, 0.8598])


torch.Size([3])

###Reshaping tensors

In [20]:
x = torch.rand(5,6)
print("Size of x :\n",x.size())
print("x:\n",x)
y = x.view(30)
print("Size of y :\n",y.size())
print("y:\n",y)
z = x.view(-1,10)
print("Size of z :\n",z.size())
print("z:\n",z)


Size of x :
 torch.Size([5, 6])
x:
 tensor([[0.2595, 0.3434, 0.8375, 0.8137, 0.7248, 0.2170],
        [0.1222, 0.3888, 0.8848, 0.0931, 0.2992, 0.2950],
        [0.5938, 0.3162, 0.4360, 0.4980, 0.7449, 0.9342],
        [0.5881, 0.2990, 0.4171, 0.9835, 0.9001, 0.6859],
        [0.1144, 0.6894, 0.1579, 0.8296, 0.0023, 0.9930]])
Size of y :
 torch.Size([30])
y:
 tensor([0.2595, 0.3434, 0.8375, 0.8137, 0.7248, 0.2170, 0.1222, 0.3888, 0.8848,
        0.0931, 0.2992, 0.2950, 0.5938, 0.3162, 0.4360, 0.4980, 0.7449, 0.9342,
        0.5881, 0.2990, 0.4171, 0.9835, 0.9001, 0.6859, 0.1144, 0.6894, 0.1579,
        0.8296, 0.0023, 0.9930])
Size of z :
 torch.Size([3, 10])
z:
 tensor([[0.2595, 0.3434, 0.8375, 0.8137, 0.7248, 0.2170, 0.1222, 0.3888, 0.8848,
         0.0931],
        [0.2992, 0.2950, 0.5938, 0.3162, 0.4360, 0.4980, 0.7449, 0.9342, 0.5881,
         0.2990],
        [0.4171, 0.9835, 0.9001, 0.6859, 0.1144, 0.6894, 0.1579, 0.8296, 0.0023,
         0.9930]])


###Generating Numbers in Sequence

In [21]:
x = torch.arange(9)
x = x.view(3,3)
print(x)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


###Concatenating two tensors at a given dimension

In [22]:
print(torch.cat((x,x),dim=0))
print(torch.cat((x,x),dim=1))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5],
        [6, 7, 8, 6, 7, 8]])


###Reducing the redundant dimension by squeeze operation

In [23]:
x1= torch.rand(1,5)
print("size of x1 squeezing:\n",x1.size())
print(x1)
x1 = x1.squeeze()
print("size of x1 after squeezing:\n", x1.size())
print(x1)

size of x1 squeezing:
 torch.Size([1, 5])
tensor([[0.8544, 0.1375, 0.3263, 0.1262, 0.1237]])
size of x1 after squeezing:
 torch.Size([5])
tensor([0.8544, 0.1375, 0.3263, 0.1262, 0.1237])


In [24]:
x1= torch.rand(1,1,5)
print("size of x1 before squeezing:\n",x1.size())
print(x1)
x1 = x1.squeeze()
print("size of x1 after squeezing:\n", x1.size())
print(x1)

size of x1 before squeezing:
 torch.Size([1, 1, 5])
tensor([[[0.4655, 0.7681, 0.6470, 0.2527, 0.4086]]])
size of x1 after squeezing:
 torch.Size([5])
tensor([0.4655, 0.7681, 0.6470, 0.2527, 0.4086])


In [25]:
x2 = torch.rand(3,1,4,1,5)
print("size of x2 before squeezing:\n",x2.size())
x2 = x2.squeeze()
print("size of x2 after squeezing:\n", x2.size())

size of x2 before squeezing:
 torch.Size([3, 1, 4, 1, 5])
size of x2 after squeezing:
 torch.Size([3, 4, 5])


###Extending the dimension by unsqueeze operation

In [26]:
x = torch.rand(3,4,5,6)
print(x.size())
print(x.unsqueeze(dim=2).size())
print(x.unsqueeze(dim=3).size())
print(x.unsqueeze(dim=4).size())

torch.Size([3, 4, 5, 6])
torch.Size([3, 4, 1, 5, 6])
torch.Size([3, 4, 5, 1, 6])
torch.Size([3, 4, 5, 6, 1])


###Numpy Bridge
####Converting a numpy array to torch tensor

In [27]:
x = np.array([[1.0,2],[3,4]])
y = torch.from_numpy(x)
print(y)
y.type()

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


'torch.DoubleTensor'

####Converting a torch tensor to numpy array

In [ ]:
z = y.numpy()
z.dtype

**CUDA Tensors**

####Checking the availability of CUDA/GPU

In [28]:
torch.cuda.is_available()

True

In [29]:
#Linux bash command to print the status of nvidia gpu (memory and processes) 
!nvidia-smi

Fri Dec 18 02:40:38 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.45.01    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P8    10W /  70W |     10MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

####Defining the device object (cpu/gpu)

In [30]:
device = torch.device("cuda")
x = torch.rand(3,3)
print(x)
x.type()

tensor([[0.3893, 0.0608, 0.0216],
        [0.6664, 0.7718, 0.4867],
        [0.3870, 0.1677, 0.0938]])


'torch.FloatTensor'

In [31]:
x = x.to(device) # move the data to cuda
x.type()

'torch.cuda.FloatTensor'


###Transferring the tensor to the respective device (here cpu->gpu)
####Transferring the tensor from gpu->cpu


In [32]:
#Transferring the tensor from gpu->cpu
device_cpu = torch.device("cpu")
x = x.to(device_cpu)
x.type()

'torch.FloatTensor'

# For Learnable parameters we should set the variables as '**True**' required_grad

In [36]:
import torch
from torch.autograd import Variable
N, D_in, H, D_out=64,1000,100,10
x=Variable(torch.randn(N, D_in), requires_grad=False)
y=Variable(torch.randn(N, D_out), requires_grad=False)
w1=Variable(torch.randn(D_in,H), requires_grad=True)
w2=Variable(torch.randn(H, D_out), requires_grad=True)
learning_rate=1e-6
for t in range(500):
    y_pred=x.mm(w1).clamp(min=0).mm(w2)
    loss=(y_pred-y).pow(2).sum()
    loss.backward()
    w1.data-=learning_rate*w1.grad
    w2.data-=learning_rate*w2.grad
    w1.grad.data.zero_()
    w2.grad.data.zero_()