In [28]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [66]:
sentences = ["Joe waited for the train", "The train was late", "Mary and Samantha took the bus", "I looked for Mary and Samantha at the bus station" ,"Mary and Samantha arrived at the bus station early but waited until noon for the bus"]



Step 1: Tokenize a sentence
We will start by removing stopwords from the sentences.

Tokenization is the act of breaking up a sequence of strings into pieces such as words

In [60]:
def word_extraction(sentence):
      ignore = ['a', "the", "is"]    
      words = re.sub("[^\w]", " ",  sentence).split()    
      cleaned_text = [w.lower() 
      for w in words if w not in ignore]    
      return cleaned_text


In [72]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords 
nltk.download('stopwords')
set(stopwords.words('english'))

import spacy
nlp = spacy.load("en_core_web_sm")



import re

#set(stopwords.words('english'))



[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [83]:
def tokenize(sentences):
      words = []    
      for sentence in sentences:        
        w = word_extraction(sentence)        
        words.extend(w)            
        words = sorted(list(set(words)))    
      return words


In [84]:
tokenize(sentences)

['and',
 'arrived',
 'at',
 'bus',
 'but',
 'early',
 'for',
 'i',
 'joe',
 'late',
 'looked',
 'mary',
 'noon',
 'samantha',
 'station',
 'the',
 'took',
 'train',
 'until',
 'waited',
 'was']

Step 3: Build vocabulary and generate vectors


In [102]:
import numpy as np
def generate_bow(allsentences):
          vocab = tokenize(allsentences)
          print("Word List for Document \n{0} \n".format(vocab));
          for sentence in allsentences:
            words = word_extraction(sentence)        
            bag_vector = np.zeros(len(vocab))        
            for w in words:            
              for i,word in enumerate(vocab):                
                if word == w:                     
                  bag_vector[i] += 1                            
            print("{0}\n{1}\n".format(sentence,np.array(bag_vector)))



In [103]:
allsentences = ["Joe waited for the train train", "The train was late", "Mary and Samantha took the bus", 
                "I looked for Mary and Samantha at the bus station",
                "Mary and Samantha arrived at the bus station early but waited until noon for the bus"]

                


 the more similar the words in two documents, the more similar the documents can be.

In [104]:
generate_bow(allsentences)


Word List for Document 
['and', 'arrived', 'at', 'bus', 'but', 'early', 'for', 'i', 'joe', 'late', 'looked', 'mary', 'noon', 'samantha', 'station', 'the', 'took', 'train', 'until', 'waited', 'was'] 

Joe waited for the train train
[0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 1. 0.]

The train was late
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1.]

Mary and Samantha took the bus
[1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0.]

I looked for Mary and Samantha at the bus station
[1. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0.]

Mary and Samantha arrived at the bus station early but waited until noon for the bus
[1. 1. 1. 2. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 0.]



In [105]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(allsentences)
print(X.toarray())


[[0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 2 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1]
 [1 0 0 1 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0]
 [1 0 1 1 0 0 1 0 0 1 1 0 1 1 1 0 0 0 0 0]
 [1 1 1 2 1 1 1 0 0 0 1 1 1 1 2 0 0 1 1 0]]


Example of the Bag-of-Words Model
Step 1: Collect Data
let’s treat each line as a separate “document” and the 4 lines as our entire corpus of documents.






Step 2: Design the Vocabulary
The unique words here (ignoring case and punctuation) are: That is a vocabulary of 10 words from a corpus containing 24 words.

Step 3: Create Document Vectors
 score the words in each document: turn each document of free text into a vector that we can use as input or output for a machine learning model.
 **we can use a fixed-length document representation of vocabluary size with one position in the vector to score each word.The simplest scoring method is to mark the presence of words as a boolean value, 0 for absent, 1 for present.





New documents that overlap with the vocabulary of known words, but may contain words outside of the vocabulary, can still be encoded, where only the occurrence of known words are scored and unknown words are ignored.



Managing Vocabulary
As the vocabulary size increases, so does the vector representation of documents.
the length of the document vector is equal to the number of known words.
You can imagine that for a very large corpus, such as thousands of books, that the length of the vector might be thousands or millions of positions. Further, each document may contain very few of the known words in the vocabulary.

*****
This results in a vector with lots of zero scores, called a sparse vector or sparse representation.
**Sparse vectors require more memory and computational resources when modeling and the vast number of positions or dimensions can make the modeling process very challenging for traditional algorithms.





As such, there is pressure to decrease the size of the vocabulary of BOW model using simple text cleaning techniques: 

1.   Ignoring case
2.   Ignoring punctuation




Ignoring frequent words that don’t contain much information, called stop words, like “a,” “of,” etc.
Fixing misspelled words.
Reducing words to their stem (e.g. “play” from “playing”) using stemming algorithms.

A more sophisticated approach is to create a vocabulary of grouped words. This both changes the scope of the vocabulary and allows the bag-of-words to capture a little bit more meaning from the document.



*    each word or token is called a “gram”. Creating a vocabulary of two-word pairs is, in turn, called a bigram model. 
Again, only the bigrams that appear in the corpus are modeled, not all possible bigrams.

An N-gram is an N-token sequence of words: a 2-gram (more commonly called a bigram) is a two-word sequence of words like “please turn”, “turn your”, or “your homework”, and a 3-gram (more commonly called a trigram) is a three-word sequence of words like “please turn your”, or “turn your homework”.




For example, the bigrams in the first line of text in the previous section: “It was the best of times” are as follows:

“it was”
“was the”
“the best”
“best of”
“of times”


*  A vocabulary then tracks triplets of words is called a trigram model and the general approach is called the n-gram model, where n refers to the number of grouped words.


*   Often a simple bigram approach is better than a 1-gram bag-of-words model for tasks like documentation classification.





**Scoring Words**
Once a vocabulary has been chosen, the occurrence of words in example documents needs to be scored.

In the worked example, we have already seen one very simple approach to scoring: a binary scoring of the presence or absence of words.

**Some additional simple scoring methods include:**


*   Counts. Count the number of times each word appears in a document.
*   Frequencies. Calculate the frequency that each word appears in a document out of all the words in the document.




**Word Hashing**
a hash function is a bit of math that maps data to a fixed size set of numbers.
hash tables when programming where perhaps names are converted to numbers for fast lookup.


*   hash representation of known words in our vocabulary. This addresses the problem of having a very large vocabulary for a large text corpus because we can choose the size of the hash space, which is in turn the size of the vector representation of the document.


*  Words are hashed deterministically to the same integer index in the target hash space. A binary score or count can then be used to score the word.


*   This is called the “hash trick” or “feature hashing“.


*   The challenge is to choose a hash space to accommodate the chosen vocabulary size to minimize the probability of collisions and trade-off sparsity.






**TF-IDF**
A problem with scoring word frequency is that highly frequent words start to dominate in the document (e.g. larger score), but may not contain as much “informational content” to the model as rarer but perhaps domain specific words.



*   One approach is to rescale the frequency of words by how often **they appear in all documents,** so that the scores for frequent words like “the” that are also frequent across all documents are penalized.


*  This approach to scoring is called Term Frequency – Inverse Document Frequency, or TF-IDF for short, where:


1.  **Term Frequency**: is a scoring of the frequency of the word in the current document.
2.  **Inverse Document Frequency**: is a scoring of how rare the word is across documents.


The scores are a weighting where not all words are equally as important or interesting.


The scores have the effect of highlighting words that are distinct (contain useful information) in a given document. **Thus the idf of a rare term is high, whereas the idf of a frequent term is likely to be low.**






**Limitations of Bag-of-Words**


1.   **Vocabulary**: The vocabulary requires careful design, most specifically in order to manage the size, which impacts the sparsity of the document representations.
2.   **Sparsity**: Sparse representations are harder to model both for computational reasons (space and time complexity) and also for information reasons, where the challenge is for the models to harness so little information in such a large representational space.


1.   **Meaning**: Discarding word order ignores the context, and in turn meaning of words in the document (semantics). Context and meaning can offer a lot to the model, that if modeled could tell the difference between the same words differently arranged (“this is interesting” vs “is this interesting”), synonyms (“old bike” vs “used bike”), and much more.

2.



