In [13]:
from scipy.special import softmax
import numpy as np
import math 
 

In [20]:
x_t = np.array([[1, 2, 3]])
x_t_1 = np.array([[1, 2, 3]])
h_t_min_1 = np.array([[0, 0]])

U = np.array([[1,2],
              [2,3],
              [1,1]
                ])

W = np.array([[1,1],
              [2,2]])

V = np.array([[1],
              [5]])


In [37]:
def fun_h(U,x,W,h):
    r1 = np.matmul(x, U)
    r2 = np.matmul(h, W)
    return r1 + r2

In [38]:
h_t = fun_h(U,x_t, W, h_t_min_1)
h_t

array([[ 8, 11]])

In [41]:
o_t = softmax(np.matmul(V, h_t))
o_t

array([[3.87399644e-21, 7.78112986e-20],
       [3.05902227e-07, 9.99999694e-01]])

In [42]:
def softmax(x, axis):
    x -= np.max(x, axis=axis, keepdims=True)
    return np.exp(x) / np.exp(x).sum(axis=axis, keepdims=True)

In [47]:
x = np.matmul(V, h_t)
softmax(x, axis=1).round(2)


array([[0.05, 0.95],
       [0.  , 1.  ]])

In [57]:
h_t_plus_1 = fun_h(U, x_t_1,  W,h_t)
h_t_plus_1

array([[38, 41]])